### ISSUE TITLE
Windows support for diskDriver

### ISSUE THREAD

**Issue by sortofdev** [blockstack/gaia#133]
By attemping to run a Gaia server on Windows 10 machine with default **config.json** (copy of config.sample.disk.json) following error shows up:
`src\server\server.js -> lib\server\server.js`

`
"function":"Module._load","line":489,"method":"_load","native":false}],"stack":["Error: UNKNOWN: unknown error, lstat '\\\\Users\\home\\'","    at Object.fs.lstatSync (fs.js:941:11)","    at DiskDriver.mkdirs (C:\\Users\\home\\dev\\gaia\\hub\\lib\\server\\drivers\\diskDriver.js:56:39)","    at new DiskDriver (C:\\Users\\home\\dev\\gaia\\hub\\lib\\server\\drivers\\diskDriver.js:41:10)","    at makeHttpServer (C:\\Users\\home\\dev\\gaia\\hub\\lib\\server\\http.js:51:14)","    at Object.<anonymous> (C:\\Users\\home\\dev\\gaia\\hub\\lib\\index.js:15:36)","    at Module._compile (module.js:635:30)","    at Object.Module._extensions..js (module.js:646:10)","    at Module.load (module.js:554:32)","    at tryModuleLoad (module.js:497:12)","    at Function.Module._load (module.js:489:3)"],"level":"error","message":"uncaughtException: UNKNOWN: unknown error, lstat '\\\\Users\\home\\'","timestamp":"2018-07-21T08:04:56.676Z"
`

Tried creating the /tmp/gaia-data folder on main drive manually, that did not seem to help. Neither did changing paths in config.json have any positive results, always ending up with the same error, but with different paths.

Mac OS did not seem to have this issue, I'm not sure if Gaia server is even supposed to run on Windows, if not it would be a good idea to mention that in README file.

**Comment by kantai** [comment]
Hi @sortofdev -- the gaia disk driver does indeed require a *nix filesystem interface. Will add a note to the readme to indicate such

**Comment by zone117x** [comment]
Should we re-open this issue so its a bit more on the radar for us?
I'm assuming most devs who pull Gaia for local dev/testing use the disk driver? If so it seems like this issue would be excluding most Windows devs?

**Comment by markmhx** [comment]
In theory I'm in support of getting the driver to work on Windows, though I'm not sure how much work it'd take? Perhaps @kantai has the best idea

**Comment by markmhx** [comment]
Sounds good, I'd say forge ahead then.

**Comment by zone117x** [comment]
It is likely this was fixed with changes from around a year ago, but hasn't been tested. 
Closing this issue due to lack of activity. Please feel free to comment if this should be re-opened.
